#+ endpoint: https://query.wikidata.org/sparql

SELECT ?author ?authorLabel ?image ?genderLabel ?nationalityLabel ?birth_date ?birth_placeLabel ?educationLabel

WHERE {
?author wdt:P1411 wd:Q37922 .
?author wdt:P31 wd:Q5 .
OPTIONAL { ?author wdt:P21 ?gender . } . 
OPTIONAL { ?author wdt:P27 ?nationality . } . 
OPTIONAL { ?author wdt:P569 ?birth_date .} . 
OPTIONAL { ?author wdt:P19 ?birth_place .} . 
OPTIONAL { ?author wdt:P69 ?education . } . 
OPTIONAL { ?author wdt:P18 ?image . } .
                                                                                                            
 SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en".}
}
